config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  resources :admins
  resources :hr
  resources :employees
  get '/download/:id',to: 'admins#download', as: "download"
  namespace :api do
    namespace :v1,defaults: { format: :json } do
      resources :admins , expect: :destroy do

      end
      resources :employees,:hr
     get '/delete_all', to: 'admins#index' 
    end

  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/employee.rb
class Employee < ApplicationRecord
    belongs_to :admin
    has_many_attached :images
    validates :name, :age,:phone_no,:address,presence: true
    validates :phone_no, format: { with: /\A\d{10}\z/,message: "only allows 10 munbers" }

    # validates :email, format: { with: Devise.email_regexp }
    # validate :age_verify
    # def age_verify
    #     if age < 18
    #       errors.add(:age, "can't be lessthan 18") 
    #     end
    # end
end

app/controllers/api/v1/employees_controller.rb
class Api::V1::EmployeesController < Api::V1::ApiController
    skip_before_action :verify_authenticity_token
    before_action :set_employee, only: [:show, :update, :destroy]
    def index
      @employees = Employee.all
    end
    def show
     
    end
    def create
        @admin =Admin.first
        @employee = @admin.Employees.new(employee_params)
        if @employee.save
            render :create
        else
            render json: {status:"error",message:"not saved",data:@employee.errors}
        end   
    end
    def update
        if @employee.update(employee_params)
            render :update
        else
            render json: {status:"error",message:"not update",data:@employee.errors}
        end
    end
    def destroy
        if @employee.destroy
            redirect_to api_v1_employees_path
        end
    end
    private
    def set_employee
        @employee = Employee.find(params[:id])
    end
    def employee_params
        params.permit(:name,:phone_no,:email,:age,:address)
    end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
    before_action :set_employee, only: [:show, :edit,:update,:destroy]
    load_and_authorize_resource
    def index
      @employees =Employee.all
    end
    def show
    end
    def new
      @employee = Employee.new
    end
    def create
      @admin =Admin.first
      @employee = @admin.employees.new(employee_params)
      if @employee.save
        redirect_to employees_path
      else
        render :new
      end
    end



    def edit
    end
    
    
    def update
      if @employee.update(employee_params)
        redirect_to  employees_path
      else
        render :edit
      end
    end

    def destroy
      @employee.destroy
      redirect_to employees_path
    end
    private
    def set_employee
      @employee = Employee.find(params[:id])
    end
    def employee_params
      params.require(:employee).permit(:name,:phone_no,:email,:age,:address, images: [])
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/edit.html.erb
<%= form_with model:@employee, url:employee_path , method: :patch do |f| %>
 <div>
    <%= f.label :name %><br />
    <%= f.text_field :name%>
  </div> 
  <div>
      <%= f.label :phone_no %><br />
      <%= f.text_field :phone_no%>
    </div>
    <div>
      <%= f.label :email %> <br>
      <%= f.email_field :email %>
    </div> 
 
  <div>
    <%= f.label :age %><br />
    <%= f.text_field :age%>
  </div>

  <div>
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div> 

  <div>
    <%= f.label :images %><br />
    <%= f.file_field :images, multiple: true  %>
  </div> 

  <div>
    <%= f.submit  %>
  </div>

<% end %>

app/views/employees/index.html.erb
<h1>Employee dashbord</h1>
<table>
    <tr>
        <th>name</th>
    </tr>
    <% @employees.each do |employee| %>
    <tr>
        <td><%=employee.name %></td>
        <td><%=link_to "Profile",employee_path(employee.id) %></td>
        <td><%=link_to "Edit",edit_employee_path(employee.id) %></td>
        <td><%=link_to "Delete",employee_path(employee.id), method: :delete%></td>
    </tr>
    <% end %>
</table><br>
<%= link_to "Add Employee",new_employee_path %><br>
<%= link_to "Admin Dashboard",admins_path %><br>
<%= link_to "hr dashboard",hr_index_path %><br><br>

app/views/employees/new.html.erb
<h1>New Employeee</h1>

<%= form_with model:@employee,url:employees_path , method: :post do |f| %>
 <div>
    <%= f.label :name %><br />
    <%= f.text_field :name%>
  </div> 
  
  <div>
    <%= f.label :phone_no %><br />
    <%= f.text_field :phone_no%>
  </div>
  <div>
    <%= f.label :email %> <br>
    <%= f.email_field :email %>
  </div> 
  <div>
    <%= f.label :age %><br />
    <%= f.text_field :age%>
  </div>

  <div>
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div> 
   <div>
    <%= f.label :images %><br />
    <%= f.file_field :images, multiple: true  %>
  </div> 
  <div>
    <%= f.submit  %>
  </div>

<% end %>

app/views/employees/show.html.erb
<h1>Profile</h1>

id : <%=@employee.id %> <br>
name : <%=@employee.name %><br>
phone_no : <%=@employee.phone_no %><br>
email : <%=@employee.email %><br>
age : <%=@employee.age %><br>
address : <%=@employee.address %><br>
<% @employee.images.each do |image| %>
<%= image_tag image,width: "200px" ,height: "200px" %>
<% end %><br>
<%= link_to "back",employees_path %>