config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  resources :admins
  resources :hr
  resources :employees
  get '/download/:id',to: 'admins#download', as: "download"
  namespace :api do
    namespace :v1,defaults: { format: :json } do
      resources :admins , expect: :destroy do

      end
      resources :employees,:hr
     get '/delete_all', to: 'admins#index' 
    end

  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/admins/edit.html.erb
<%= form_with model:@admin,url:admin_path(@admin.id) , method: :patch do |f| %>
 <div>
    <%= f.label :name %><br />
    <%= f.text_field :name%>
  </div> 
 
  <div>
    <%= f.label :phone_no %><br />
    <%= f.text_field :phone_no%>
  </div>
  <div>
    <%= f.label :email %> <br>
    <%= f.email_field :email %>
  </div> 
  <div>
    <%= f.label :age %><br />
    <%= f.text_field :age%>
  </div>

  <div>
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div> 
  <div>
    <%= f.label :image %><br />
    <%= f.file_field :image %>
  </div> 
  <div>
    <%= f.submit  %>
  </div>

<% end %>

app/views/admins/index.html.erb
<h1> Admin dashbord</h1>
<table>
    <tr>
        <th>name</th>
        <!-- <th>phone_no</th>
        <th>age</th>
        <th>address</th> -->
    </tr>
    <% @admin.each do |admin| %>
    <tr>
        <td><%= admin.name %></td>
        <!-- <td><%#= admin.phone_no %></td>
        <td><%#= admin.age %></td>
        <td><%#= admin.address %></td> -->
        <td><%=link_to "Profile",admin_path(admin.id) %></td>
        <td><%=link_to "Edit",edit_admin_path(admin.id) %></td>
        <td><%=link_to "Delete",admin_path(admin.id), method: :delete%></td>
    </tr>
    <% end %>
</table><br>
<%= link_to "Add Admin",new_admin_path %><br>
<%= link_to "hr dashbord",hr_index_path %><br>
<%= link_to "Employee Dashboard",employees_path %><br>

app/views/admins/new.html.erb
<%= form_with model:@admin,url:admins_path , method: :post do |f| %>
 <div>
    <%= f.label :name %><br />
    <%= f.text_field :name%>
  </div> 
   
  
  <div>
    <%= f.label :phone_no %><br />
    <%= f.text_field :phone_no%>
  </div>
  <div>
    <%= f.label :email %> <br>
    <%= f.email_field :email %>
  </div> 
  <div>
    <%= f.label :age %><br />
    <%= f.text_field :age%>
  </div>

  <div>
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div> 
  <div>
    <%= f.label :image %><br />
    <%= f.file_field :image %>
  </div> 

  <div>
    <%= f.submit  %>
  </div>

<% end %>

app/views/admins/show.html.erb
<h1>Profile</h1>

id : <%=@admin.id %> <br>
name : <%=@admin.name %><br>
phone_no : <%=@admin.phone_no %><br>
email : <%=@admin.email %><br>
age : <%=@admin.age %><br>
address : <%=@admin.address %><br>
<%if @admin.image.attached?%>
<%= image_tag(@admin.image,width: "200px" ,height: "200px") %>
<%end%><br>
<%= link_to "back",admins_path %>