config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  resources :admins
  resources :hr
  resources :employees
  get '/download/:id',to: 'admins#download', as: "download"
  namespace :api do
    namespace :v1,defaults: { format: :json } do
      resources :admins , expect: :destroy do

      end
      resources :employees,:hr
     get '/delete_all', to: 'admins#index' 
    end

  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/hr.rb
class Hr < ApplicationRecord
    belongs_to :admin, optional: true
    validates :name,:age,:phone_no,:address,presence: true
    validates :phone_no, format: { with: /\A\d{10}\z/,message: "only allows 10 munbers" }
    # validates :email, format: { with: Devise.email_regexp }
    # validate :age_verify
    # def age_verify
    #     if age < 18
    #       errors.add(:age, "can't be lessthan 18") 
    #     end
    # end
end

app/controllers/api/v1/hr_controller.rb
class Api::V1::HrController < Api::V1::ApiController
    skip_before_action :verify_authenticity_token
    before_action :set_hr, only: [:show, :update, :destroy]
    def index
      @hrs = Hr.all
    end
    def show
      
    end
    def create
        @admin =Admin.first
        @hr = @admin.hrs.new(hr_params)
        if @hr.save
            render :create
        else
            render json: {status:"error",message:"not saved",data:@hr.errors}
        end   
    end
    def update
        if @hr.update(hr_params)
            render :update
        else
            render json: {status:"error",message:"not update",data:@hr.errors}
        end
    end
    def destroy
        if @hr.destroy
            redirect_to api_v1_hr_index_path
        end
    end
    private
    def set_hr
        @hr = Hr.find(params[:id])
    end
    def hr_params
        params.permit(:name,:email,:phone_no,:age,:address)
    end
end

app/controllers/hr_controller.rb
class HrController < ApplicationController
    load_and_authorize_resource
    before_action :set_hr, only: [:show, :edit, :update, :destroy]
    def index
      @hr = Hr.all
    end
    def show
      
    end
    def new
      @hr = Hr.new
    end
    def create
      @admin =Admin.first
      @hr = @admin.hrs.new(hr_params)
      if @hr.save 
        redirect_to hr_index_path
      else
        render :new
      end
    end
    def edit
    end
    def update
      if @hr.update(hr_params)
        redirect_to  hr_index_path
      else
        render :edit
      end
    end
    def destroy
      @hr.destroy
      redirect_to hr_index_path
    end
    private
    def set_hr
      @hr = Hr.find(params[:id])
    end
    def hr_params
      params.require(:hr).permit(:name,:email,:phone_no,:age,:address)
    end
end
#https://demoproject1-app.herokuapp.com/users/sign_in

app/helpers/hr_helper.rb
module HrHelper
end

app/views/hr/edit.html.erb
<%= form_with model:@hr,url:hr_path , method: :patch do |f| %>
 <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name%>
  </div> 
  <div class="field">
    <%= f.label :email %> <br>
    <%= f.email_field :email %>
  </div> 
  <div class="field">
    <%= f.label :phone_no %><br />
    <%= f.text_field :phone_no%>
  </div>
 
  <div class="field">
    <%= f.label :age %><br />
    <%= f.text_field :age%>
  </div>

  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div> 
  <div>
    <%= f.submit  %>
  </div>

<% end %>

app/views/hr/index.html.erb
<h1>Hr dashbord</h1>
<table>
    <tr>
        <th>name</th>
        <!-- <th>phone_no</th>
        <th>age</th>
        <th>address</th> -->
    </tr>
    <% @hr.each do |hr| %>
    <tr>
        <td><%=hr.name %></td>
        <!-- <td><%=hr.phone_no %></td>
        <td><%=hr.age %></td>
        <td><%=hr.address %></td> -->
        <td><%=link_to "Profile",hr_path(hr.id) %></td>
        <td><%=link_to "Edit",edit_hr_path(hr.id) %></td>
        <td><%=link_to "Delete",hr_path(hr.id), method: :delete%></td>
    </tr>
    <% end %>
</table><br>
<%= link_to "Add hr",new_hr_path %><br>
<%= link_to "Admin Dashboard",admins_path %><br>
<%= link_to "Employee Dashboard",employees_path %><br>

app/views/hr/new.html.erb
<h1>New Hr</h1>

<%= form_with model:@hr,url:hr_index_path , method: :post do |f| %>
 <div>
    <%= f.label :name %><br />
    <%= f.text_field :name%>
  </div> 
  <div>
    <%= f.label :email %> <br>
    <%= f.email_field :email %>
  </div> 
  <div>
    <%= f.label :phone_no %><br />
    <%= f.text_field :phone_no%>
  </div>
 
  <div>
    <%= f.label :age %><br />
    <%= f.text_field :age%>
  </div>

  <div>
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div> 
  <div>
    <%= f.submit  %>
  </div>

<% end %>

app/views/hr/show.html.erb
<h1>Profile</h1>

id : <%= @hr.id %> <br>
name : <%= @hr.name %><br>
email : <%= @hr.email %><br>
phone_no : <%=@hr.phone_no %><br>
age : <%= @hr.age %><br>
address : <%= @hr.address %><br>
<%= link_to "back",hr_index_path %>